// Package guestinit generates the cloud-init user-data a VM receives on its
// first boot. That is the whole of its job: building the NoCloud seed image is
// `virt-install --cloud-init`'s work, not ours (ADR-0009), and meta-data —
// instance id and local hostname — is filled in by virt-install as well.
//
// Everything here crosses the trust boundary in the outbound direction: it is
// read by an untrusted guest and it must never carry anything the host cares
// about. Public keys are authorized here; private key material, tokens, and the
// contents of operator-supplied user-data are never logged (SECURITY.md).
//
// The generated user-data is a public contract pinned by golden files
// (AGENTS.md §8), so a change to the template is a change other software sees.
package guestinit

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"mime/multipart"
	"net/textproto"
	"os"
	"regexp"
	"strings"
	"text/template"

	"git.snaphop.xyz/snaphop/snaphop-agent-vm/internal/config"
	"git.snaphop.xyz/snaphop/snaphop-agent-vm/templates"
)

// mimeBoundary is fixed rather than random. Two identical VM configurations
// must produce byte-identical user-data, or golden files could not pin it and
// an operator could not diff one VM's seed against another's.
const mimeBoundary = "agent-vm-cloud-init"

// Options is everything the guest needs to know about itself. Key material is
// passed in already read and validated; this package does no I/O of its own
// except LoadPublicKeys.
type Options struct {
	// Hostname is the VM name, which is also the libvirt domain name.
	Hostname string
	// User is the account the operator logs in as.
	User string
	// SSHAuthorizedKeys are OpenSSH *public* keys, one per entry.
	SSHAuthorizedKeys []string
	// ExtraUserData is operator-supplied user-data from --cloud-init, verbatim.
	// It is merged as a separate MIME part rather than textually, so that a
	// malformed value cannot silently corrupt the settings above it.
	ExtraUserData []byte
	// ExtraSource is where ExtraUserData came from, used in error messages
	// only. The contents themselves are never logged or echoed.
	ExtraSource string
	// AgentVMVersion is recorded in a comment so a seed found later can be
	// traced to the build that wrote it.
	AgentVMVersion string
}

var userNamePattern = regexp.MustCompile(`^[a-z_][a-z0-9_-]{0,31}$`)

var userDataTemplate = template.Must(template.New("user-data.tmpl").
	Funcs(template.FuncMap{"yaml": yamlString}).
	ParseFS(templates.FS, "cloud-init/user-data.tmpl"))

// Generate renders the user-data for one VM. When the operator supplied their
// own user-data, the result is a MIME multipart document holding theirs and
// ours; otherwise it is a plain `#cloud-config` document.
func Generate(opts Options) ([]byte, error) {
	if err := opts.validate(); err != nil {
		return nil, err
	}

	var generated bytes.Buffer
	err := userDataTemplate.Execute(&generated, struct {
		Options
		HasExtraUserData bool
	}{opts, len(opts.ExtraUserData) > 0})
	if err != nil {
		return nil, fmt.Errorf("rendering cloud-init user-data: %w", err)
	}

	if len(opts.ExtraUserData) == 0 {
		return generated.Bytes(), nil
	}
	return combine(opts.ExtraUserData, opts.ExtraSource, generated.Bytes())
}

func (o Options) validate() error {
	if err := config.ValidateVMName(o.Hostname); err != nil {
		return err
	}
	if !userNamePattern.MatchString(o.User) {
		return &config.ValidationError{
			Field: "guest user", Value: o.User,
			Err:    fmt.Errorf("names must match %s", userNamePattern),
			Remedy: "Use a lowercase Linux account name such as `agent`.",
		}
	}
	if len(o.SSHAuthorizedKeys) == 0 {
		// A guest with no authorized key accepts no logins at all, and the
		// failure would show up as an unreachable VM minutes later.
		return &config.ValidationError{
			Field: "ssh keys", Value: "",
			Err:    fmt.Errorf("a VM needs at least one authorized SSH public key"),
			Remedy: "Pass --ssh-key <path to a .pub file>, add --host-authorized-keys, or set [guest] ssh_keys in the config file.",
		}
	}
	for _, key := range o.SSHAuthorizedKeys {
		if err := ValidatePublicKeyLine(key); err != nil {
			return err
		}
	}
	if strings.ContainsAny(o.AgentVMVersion, "\r\n") {
		return fmt.Errorf("agent-vm version %q contains a line break", o.AgentVMVersion)
	}
	return nil
}

// combine wraps the operator's user-data and ours in one multipart document.
//
// cloud-init applies the parts in order, so ours is placed last and declares
// the merge rules that make that ordering decisive (see the template). Merging
// as MIME parts rather than as text is what keeps a syntax error in the
// operator's file from being an error in the settings agent-vm requires.
func combine(extra []byte, source string, generated []byte) ([]byte, error) {
	extraType, err := partContentType(extra, source)
	if err != nil {
		return nil, err
	}

	var out bytes.Buffer
	writer := multipart.NewWriter(&out)
	if err := writer.SetBoundary(mimeBoundary); err != nil {
		return nil, fmt.Errorf("preparing the cloud-init multipart document: %w", err)
	}

	// The MIME headers have to precede the first boundary for cloud-init to
	// read the document as multipart at all.
	fmt.Fprintf(&out, "MIME-Version: 1.0\r\nContent-Type: multipart/mixed; boundary=%q\r\n\r\n", mimeBoundary)

	parts := []struct {
		contentType string
		filename    string
		body        []byte
	}{
		{extraType, "user-supplied", extra},
		{"text/cloud-config", "agent-vm", generated},
	}
	for _, part := range parts {
		header := textproto.MIMEHeader{}
		header.Set("Content-Type", part.contentType+`; charset="utf-8"`)
		header.Set("Content-Disposition", fmt.Sprintf("attachment; filename=%q", part.filename))
		w, err := writer.CreatePart(header)
		if err != nil {
			return nil, fmt.Errorf("writing the %s cloud-init part: %w", part.filename, err)
		}
		if _, err := w.Write(part.body); err != nil {
			return nil, fmt.Errorf("writing the %s cloud-init part: %w", part.filename, err)
		}
	}
	if err := writer.Close(); err != nil {
		return nil, fmt.Errorf("closing the cloud-init multipart document: %w", err)
	}
	return out.Bytes(), nil
}

// userDataPrefixes maps cloud-init's documented user-data headers to the MIME
// type that selects the handler for them. We do not guess: a payload with no
// recognized header is refused, because cloud-init would silently ignore it and
// the operator would be left with a VM that booted without their configuration.
var userDataPrefixes = []struct {
	prefix      string
	contentType string
}{
	{"#cloud-config-archive", "text/cloud-config-archive"},
	{"#cloud-config-jsonp", "text/cloud-config-jsonp"},
	{"#cloud-config", "text/cloud-config"},
	{"#cloud-boothook", "text/cloud-boothook"},
	{"#include-once", "text/x-include-once-url"},
	{"#include", "text/x-include-url"},
	{"#part-handler", "text/part-handler"},
	{"#!", "text/x-shellscript"},
}

// partContentType classifies operator-supplied user-data by its first line.
// Content-Type is how cloud-init chooses a handler inside a multipart document,
// and the headers below are the same ones it recognizes on a bare payload.
func partContentType(data []byte, source string) (string, error) {
	body := strings.TrimLeft(string(data), " \t\r\n")

	// A jinja-templated payload declares itself on the line above its real
	// header, so the header is looked for on the next line.
	if rest, ok := strings.CutPrefix(body, "## template: jinja"); ok {
		body = strings.TrimLeft(rest, " \t\r\n")
	}
	for _, candidate := range userDataPrefixes {
		if strings.HasPrefix(body, candidate.prefix) {
			return candidate.contentType, nil
		}
	}

	// The value itself is deliberately absent from this message: user-supplied
	// cloud-init data may contain secrets and is never echoed (SECURITY.md).
	known := make([]string, 0, len(userDataPrefixes))
	for _, candidate := range userDataPrefixes {
		known = append(known, candidate.prefix)
	}
	return "", &config.ValidationError{
		Field: "cloud-init user-data", Value: source,
		Err: fmt.Errorf("the file does not begin with a header cloud-init recognizes"),
		Remedy: "Start the file with one of: " + strings.Join(known, ", ") +
			". Without one, cloud-init would ignore the file instead of applying it.",
	}
}

// LoadPublicKeys reads the operator's SSH public key files and returns the key
// lines to authorize. It refuses anything that is not a public key, so private
// material cannot reach a guest even by mistake (SECURITY.md).
func LoadPublicKeys(paths []string) ([]string, error) {
	keys := []string{}
	seen := map[string]bool{}

	for _, path := range paths {
		if err := config.ValidateSSHPublicKey(path); err != nil {
			return nil, err
		}
		contents, err := os.ReadFile(path)
		if err != nil {
			return nil, &config.ValidationError{Field: "ssh key", Value: path, Err: err}
		}
		found, count, err := parseKeyLines(path, contents, seen)
		if err != nil {
			return nil, err
		}
		if count == 0 {
			return nil, &config.ValidationError{
				Field: "ssh key", Value: path,
				Err: fmt.Errorf("contains no SSH public key"),
			}
		}
		keys = append(keys, found...)
	}
	return keys, nil
}

// LoadAuthorizedKeys reads the host account's OpenSSH `authorized_keys` files —
// what `create --host-authorized-keys` authorizes — and returns the key lines
// together with the files they came from. It differs from LoadPublicKeys in
// what a file may look like: an authorized_keys file holds several keys and may
// carry comments, where a .pub file holds exactly one key on its first line.
//
// Several paths are read because a host account may keep its keys in more than
// one of them, so a file that is not there is skipped rather than being an
// error. Finding no file at all, or finding files with no key in them, is an
// error: the flag asked for keys and produced none.
//
// Entries carrying OpenSSH options (`command=`, `restrict`, `from=`) are
// refused rather than silently stripped or silently dropped: an option is a
// restriction the operator wrote down, and neither honoring it in the guest nor
// discarding it is something this tool may decide on their behalf.
func LoadAuthorizedKeys(paths []string) (keys, sources []string, err error) {
	keys, sources = []string{}, []string{}
	seen := map[string]bool{}
	total := 0

	for _, path := range paths {
		contents, err := os.ReadFile(path)
		if errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if err != nil {
			return nil, nil, &config.ValidationError{
				Field: "host authorized_keys", Value: path, Err: err,
				Remedy: hostAuthorizedKeysRemedy(paths),
			}
		}
		found, count, err := parseKeyLines(path, contents, seen)
		if err != nil {
			return nil, nil, err
		}
		keys = append(keys, found...)
		sources = append(sources, path)
		total += count
	}

	if total == 0 {
		return nil, nil, &config.ValidationError{
			Field: "host authorized_keys", Value: strings.Join(paths, ", "),
			Err:    fmt.Errorf("no authorized key was found on this host"),
			Remedy: hostAuthorizedKeysRemedy(paths),
		}
	}
	return keys, sources, nil
}

func hostAuthorizedKeysRemedy(paths []string) string {
	return "--host-authorized-keys reads " + strings.Join(paths, " and ") +
		". Drop the flag, or pass the keys with --ssh-key."
}

// parseKeyLines returns the public key lines in a file, skipping blank lines
// and comments and rejecting anything else, along with how many keys the file
// held. seen carries across files so a key given twice — by flag and by config
// file, say — appears in the guest's authorized_keys once; it is updated with
// the keys returned.
func parseKeyLines(path string, contents []byte, seen map[string]bool) (keys []string, count int, err error) {
	keys = []string{}
	for number, line := range strings.Split(string(contents), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if err := ValidatePublicKeyLine(line); err != nil {
			return nil, 0, &config.ValidationError{
				Field: "ssh key", Value: path,
				Err: fmt.Errorf("line %d is not an SSH public key", number+1),
			}
		}
		count++
		if !seen[line] {
			seen[line] = true
			keys = append(keys, line)
		}
	}
	return keys, count, nil
}

// keyLinePattern is what an OpenSSH public key line looks like: a type, a
// base64 blob, and an optional comment. Validating the shape here means the
// value can be emitted into YAML as a quoted scalar with confidence.
var keyLinePattern = regexp.MustCompile(`^[a-z0-9@.-]+ [A-Za-z0-9+/]+={0,3}( [^\x00-\x1f]*)?$`)

// ValidatePublicKeyLine reports whether line is a single OpenSSH public key.
// It is exported because keys also arrive from outside this package — the one
// a guest generates for itself is read back over ssh, and everything crossing
// that boundary is untrusted (SECURITY.md).
func ValidatePublicKeyLine(line string) error {
	if strings.Contains(line, "PRIVATE KEY") {
		return &config.ValidationError{
			Field: "ssh key", Value: "(not shown)",
			Err:    fmt.Errorf("this is a private key"),
			Remedy: "Authorize the matching public key instead. Private keys never enter a VM.",
		}
	}
	if !keyLinePattern.MatchString(line) {
		return &config.ValidationError{
			Field: "ssh key", Value: firstField(line),
			Err:    fmt.Errorf("does not look like an OpenSSH public key line"),
			Remedy: "An OpenSSH public key is one line: a key type such as ssh-ed25519, the base64 key, and an optional comment.",
		}
	}
	return nil
}

// firstField returns the leading token of a key line — enough to identify which
// key was rejected without reproducing the key itself in an error message.
func firstField(line string) string {
	if field, _, ok := strings.Cut(line, " "); ok {
		return field
	}
	return line
}

// yamlString renders a value as a double-quoted YAML scalar. Every value that
// reaches it has already been validated against a pattern, so this is the
// second of two defenses rather than the only one: quoting keeps a key comment
// containing a `#` or a `:` from changing the meaning of the document.
func yamlString(s string) string {
	var out strings.Builder
	out.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			out.WriteString(`\"`)
		case '\\':
			out.WriteString(`\\`)
		case '\n':
			out.WriteString(`\n`)
		case '\r':
			out.WriteString(`\r`)
		case '\t':
			out.WriteString(`\t`)
		default:
			out.WriteRune(r)
		}
	}
	out.WriteByte('"')
	return out.String()
}
