#!/bin/sh
# Register this guest as a GitHub Actions self-hosted runner and start it.
#
# The image build installs the runner and stops there. The value that
# registers it is supplied here, by the operator, after boot (ADR-0013).
# config.sh refuses to run as root, so registration runs as github-runner.
# svc.sh is GitHub's own service installer and runs as root. The service
# user has to be passed explicitly: omitted, svc.sh falls back to SUDO_USER,
# which on these guests is agent (ADR-0013, ADR-0017).
set -eu

# Tests point this at a fake tree. It is not a configuration setting: sudo
# clears the environment, so `sudo agent-vm-github-runner` keeps the install
# path below.
prefix=${AGENT_VM_RUNNER_PREFIX:-/opt/actions-runner}

usage() {
    cat <<'EOF'
Usage: sudo agent-vm-github-runner configure --url <https-url> (--token <registration-token> | --token-file <path>) [options]
       sudo agent-vm-github-runner remove (--token <removal-token> | --token-file <path>)

configure registers this guest with GitHub and starts the runner service.
Its value is a registration token. remove stops that service and unregisters
the guest at GitHub. Its value is a removal token. Run either as root.

configure options:
  --name <name>       Runner name. Defaults to this guest's hostname.
  --labels <labels>   Comma-separated extra labels.
  --group <name>      Runner group.
  --work <dir>        Relative job directory inside the runner folder.
  --ephemeral         Accept one job, then exit and unregister.
  --replace           Replace a runner already registered under this name.
                      A local configuration is cleared first, without a token.

Jobs run as github-runner. That account may sudo without a prompt.
--token-file may be - to read the value from stdin, and a file must be
readable only by its owner. Destroying the VM does not unregister the runner.
EOF
}

die() {
    printf '%s\n' "agent-vm-github-runner: $*" >&2
    exit 1
}

usage_error() {
    printf '%s\n' "agent-vm-github-runner: $*" >&2
    usage >&2
    exit 1
}

require_value() {
    if [ $# -lt 2 ] || [ -z "$2" ]; then
        usage_error "$1 needs a value"
    fi
    case "$2" in
        -*) usage_error "$1 must not start with -" ;;
    esac
}

read_registration() {
    if [ -n "$registration" ] && [ -n "$token_file" ]; then
        usage_error "pass only one of --token and --token-file"
    fi
    if [ -z "$registration" ] && [ -z "$token_file" ]; then
        usage_error "--token or --token-file is required"
    fi
    if [ -n "$token_file" ]; then
        if [ "$token_file" = "-" ]; then
            registration=$(cat)
        else
            if [ ! -f "$token_file" ]; then
                die "--token-file must be a regular file, or - for stdin"
            fi
            mode=$(stat -c %a "$token_file")
            case "$mode" in
                400 | 600 | 0400 | 0600) ;;
                *) die "--token-file must be readable only by its owner" ;;
            esac
            registration=$(cat "$token_file")
        fi
    fi
    case "$registration" in
        "" | *[![:graph:]]*) die "--token must be a single visible value" ;;
    esac
}

validate_name() {
    case "$1" in
        [A-Za-z0-9]*) ;;
        *) die "--name must start with a letter or digit" ;;
    esac
    case "$1" in
        *[!A-Za-z0-9._-]*) die "--name may contain only letters, digits, dots, underscores, and hyphens" ;;
    esac
}

validate_label() {
    case "$1" in
        "" | *[!A-Za-z0-9._-]*) die "--labels entries may contain only letters, digits, dots, underscores, and hyphens" ;;
    esac
}

require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        die "run as root: sudo agent-vm-github-runner ..."
    fi
}

require_runner() {
    if [ ! -x "$prefix/config.sh" ]; then
        die "$prefix/config.sh is missing; this guest was not built from a runner image"
    fi
}

run_as_runner() {
    if command -v runuser >/dev/null 2>&1; then
        runuser -u github-runner -- "$@"
    else
        sudo --user github-runner -- "$@"
    fi
}

# svc.sh records the directory it is started in as the runner root, so it
# has to be started from the install directory. It is generated by config.sh
# and is not in the image before the first registration.
run_svc() {
    if [ ! -x "$prefix/svc.sh" ]; then
        return 1
    fi
    (cd "$prefix" && ./svc.sh "$@")
}

uninstall_service() {
    if [ -x "$prefix/svc.sh" ]; then
        run_svc uninstall
    fi
}

cmd=${1:-}
case "$cmd" in
    -h | --help)
        usage
        exit 0
        ;;
    "")
        usage >&2
        exit 1
        ;;
    configure | remove) shift ;;
    *) die "unknown command $cmd" ;;
esac

url=
name=
labels=
group=
work=
registration=
token_file=
ephemeral=0
replace=0

while [ $# -gt 0 ]; do
    case "$1" in
        --url)
            require_value "$@"
            url=$2
            shift 2
            ;;
        --token)
            require_value "$@"
            registration=$2
            shift 2
            ;;
        --token-file)
            if [ $# -lt 2 ] || [ -z "$2" ]; then
                usage_error "--token-file needs a path"
            fi
            token_file=$2
            shift 2
            ;;
        --name)
            require_value "$@"
            name=$2
            shift 2
            ;;
        --labels)
            require_value "$@"
            labels=$2
            shift 2
            ;;
        --group)
            require_value "$@"
            group=$2
            shift 2
            ;;
        --work)
            require_value "$@"
            work=$2
            shift 2
            ;;
        --ephemeral)
            ephemeral=1
            shift
            ;;
        --replace)
            replace=1
            shift
            ;;
        *)
            usage_error "unknown argument $1"
            ;;
    esac
done

if [ "$cmd" = "remove" ]; then
    if [ -n "$url" ] || [ -n "$name" ] || [ -n "$labels" ] || [ -n "$group" ] || [ -n "$work" ] || [ "$ephemeral" -ne 0 ] || [ "$replace" -ne 0 ]; then
        usage_error "remove accepts only --token or --token-file"
    fi
fi

read_registration

if [ "$cmd" = "configure" ]; then
    case "$url" in
        https://*) ;;
        *) usage_error "--url must be an https URL" ;;
    esac
    case "$url" in
        *[[:space:]]*) usage_error "--url must not contain whitespace" ;;
    esac
    if [ -z "$name" ]; then
        if [ -f /etc/hostname ]; then
            name=$(tr -d '[:space:]' </etc/hostname)
        fi
    fi
    if [ -z "$name" ]; then
        die "pass --name; this guest has no hostname yet"
    fi
    validate_name "$name"
    if [ -n "$labels" ]; then
        rest=$labels
        while [ -n "$rest" ]; do
            label=${rest%%,*}
            validate_label "$label"
            if [ "$rest" = "$label" ]; then
                rest=
            else
                rest=${rest#*,}
            fi
        done
    fi
    if [ -n "$group" ]; then
        case "$group" in
            [A-Za-z0-9]*) ;;
            *) die "--group must start with a letter or digit" ;;
        esac
        case "$group" in
            *[![:graph:][:space:]]*) die "--group contains a character this command will not pass on" ;;
        esac
    fi
    if [ -n "$work" ]; then
        case "$work" in
            /* | *".."*) die "--work must be a relative path inside the runner directory" ;;
        esac
        case "$work" in
            *[!A-Za-z0-9._/-]*) die "--work may contain only letters, digits, dots, underscores, hyphens, and slashes" ;;
        esac
    fi
fi

require_root
require_runner
cd "$prefix"

if [ "$cmd" = "remove" ]; then
    if [ ! -f "$prefix/.runner" ]; then
        die "this guest is not registered"
    fi
    # config.sh remove --token accepts a removal token and deletes the runner
    # at GitHub. The service has to be uninstalled first; config.sh refuses
    # the removal while it is still installed.
    uninstall_service
    run_as_runner "$prefix/config.sh" remove --token "$registration"
    exit 0
fi

if [ -f "$prefix/.runner" ]; then
    if [ "$replace" -ne 1 ]; then
        die "this guest is already registered; pass --replace to register it again"
    fi
    # config.sh refuses to configure a directory that already has .runner,
    # including when --replace is set. remove --local deletes .runner and
    # .credentials and leaves the GitHub runner in place, so the registration
    # below can replace it. The service has to be uninstalled first.
    uninstall_service
    run_as_runner "$prefix/config.sh" remove --local
fi

set -- --unattended --url "$url" --name "$name" --token "$registration"
if [ -n "$labels" ]; then
    set -- "$@" --labels "$labels"
fi
if [ -n "$group" ]; then
    set -- "$@" --runnergroup "$group"
fi
if [ -n "$work" ]; then
    set -- "$@" --work "$work"
fi
if [ "$ephemeral" -eq 1 ]; then
    set -- "$@" --ephemeral
fi
if [ "$replace" -eq 1 ]; then
    set -- "$@" --replace
fi

run_as_runner "$prefix/config.sh" "$@"
if [ ! -x "$prefix/svc.sh" ]; then
    die "config.sh did not write svc.sh"
fi
run_svc install github-runner
run_svc start
